# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Docker@2
  inputs:
    containerRegistry: 'Testcon'
    command: 'login'
- task: CmdLine@2
  inputs:
    script: |
      docker pull bitnami/jenkins:2.332.3-debian-11-r3
      docker tag bitnami/jenkins:2.332.3-debian-11-r3 repository0.eng.kmcs.io/dss-test/bitnami/jenkins:2.332.3-debian-11-r3
      docker push repository0.eng.kmcs.io/dss-test/bitnami/jenkins:2.332.3-debian-11-r3